/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: process.env.DARK_MODE ? process.env.DARK_MODE : 'class',
  content: [
    './app/**/*.{html,js,jsx,ts,tsx,mdx}',
    './components/**/*.{html,js,jsx,ts,tsx,mdx}',
    './utils/**/*.{html,js,jsx,ts,tsx,mdx}',
    './*.{html,js,jsx,ts,tsx,mdx}',
    './src/**/*.{html,js,jsx,ts,tsx,mdx}',
  ],
  presets: [require('nativewind/preset')],
  important: 'html',
  safelist: [
    {
      pattern:
        /(bg|border|text|stroke|fill)-(primary|secondary|tertiary|error|success|warning|info|typography|outline|background|indicator)-(0|50|100|200|300|400|500|600|700|800|900|950|white|gray|black|error|warning|muted|success|info|light|dark|primary)/,
    },
  ],
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#5c5b5b",
        "tertiary-fixed-dim": "#ff7c62",
        "background": "#f9f6f5",
        "tertiary-dim": "#9d1901",
        "on-tertiary-fixed-variant": "#751000",
        "surface-variant": "#dedcdc",
        "inverse-on-surface": "#9e9c9c",
        "primary": "#414BEA",
        "primary-fixed": "#9097ff",
        "on-error": "#ffefef",
        "secondary-dim": "#5321d9",
        "primary-dim": "#2b34d8",
        "error": "#b41340",
        "tertiary": "#af270c",
        "error-container": "#f74b6d",
        "surface": "#f9f6f5",
        "on-secondary": "#f6f0ff",
        "on-primary-container": "#000282",
        "on-secondary-fixed": "#3600a3",
        "on-secondary-container": "#4a0cd1",
        "on-surface": "#2f2f2e",
        "primary-fixed-dim": "#7f88ff",
        "secondary-fixed": "#d6cbff",
        "secondary": "#5f34e5",
        "surface-dim": "#d6d4d3",
        "tertiary-fixed": "#ff937d",
        "error-dim": "#a70138",
        "outline-variant": "#afadac",
        "inverse-primary": "#7b85ff",
        "secondary-fixed-dim": "#c8bbff",
        "on-tertiary-container": "#650c00",
        "secondary-container": "#d6cbff",
        "outline": "#787676",
        "on-primary": "#f3f1ff",
        "on-tertiary": "#ffefec",
        "inverse-surface": "#0e0e0e",
        "surface-tint": "#414BEA",
        "on-primary-fixed-variant": "#00029e",
        "on-tertiary-fixed": "#370400",
        "on-error-container": "#510017",
        "on-primary-fixed": "#000000",
        "surface-container-high": "#e4e2e1",
        "surface-container": "#eae7e7",
        "on-background": "#2f2f2e",
        "tertiary-container": "#ff937d",
        "surface-container-highest": "#dedcdc",
        "on-secondary-fixed-variant": "#5423da",
        "primary-container": "#9097ff",
        "surface-container-low": "#f3f0ef",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#f9f6f5"
      },
      fontFamily: {
        heading: ['SpaceGrotesk_700Bold', 'SpaceGrotesk_400Regular'],
        body: ['Manrope_400Regular', 'Manrope_500Medium', 'Manrope_700Bold'],
        mono: ['SpaceMono_400Regular'],
        headline: ['SpaceGrotesk_700Bold'],
        label: ['SpaceMono_400Regular'],
        jakarta: ['var(--font-plus-jakarta-sans)'],
        roboto: ['var(--font-roboto)'],
        code: ['var(--font-source-code-pro)'],
        inter: ['var(--font-inter)'],
        'space-mono': ['SpaceMono_400Regular'],
        poppins: ['Poppins_400Regular', 'Poppins_700Bold'],
      },
      fontWeight: {
        extrablack: '950',
      },
      fontSize: {
        '2xs': '10px',
      },
      boxShadow: {
        'hard-1': '-2px 2px 8px 0px rgba(38, 38, 38, 0.20)',
        'hard-2': '0px 3px 10px 0px rgba(38, 38, 38, 0.20)',
        'hard-3': '2px 2px 8px 0px rgba(38, 38, 38, 0.20)',
        'hard-4': '0px -3px 10px 0px rgba(38, 38, 38, 0.20)',
        'hard-5': '0px 2px 10px 0px rgba(38, 38, 38, 0.10)',
        'soft-1': '0px 0px 10px rgba(38, 38, 38, 0.1)',
        'soft-2': '0px 0px 20px rgba(38, 38, 38, 0.2)',
        'soft-3': '0px 0px 30px rgba(38, 38, 38, 0.1)',
        'soft-4': '0px 0px 40px rgba(38, 38, 38, 0.1)',
      },
    },
  },
};
